name: node.reconnecting-websocket Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GH_TOKEN: ${{secrets.UTILITY_GH_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@superbet-group'
      - run: echo //npm.pkg.github.com/:_authToken=$GH_TOKEN >> .npmrc
      - run: echo @superbet-group:registry=https://npm.pkg.github.com/superbet-group >> .npmrc
      - run: npm install
      - run: npm run build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
